# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjIxZGY1MjIwMjdkYTk5ZjAxYTliZjU2MmZlOGRkMGNmZTJhNGVjODI4Y2NjOGI3MzYzMDVlMDEwZWZiNzJiMTY4MTJmM2Q1MGM0NDNiNDMyYjQxMjM4YjQ0NzczNjAyMjk0OTgzYTk1NjI5ODIzZGRjMDcxMTM5OWVhNjM0YzU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
